import { describe, expect, it } from 'vitest';
import type { FileResult } from '../../../src/core/model';
import { resolveSchema } from '../../../src/core/resolve';
import { entParser } from '../../../src/parsers/ent';

const parse = (path: string, text: string) => entParser.parse({ path, text });
const fr = (path: string, text: string): FileResult => ({ file: path, kind: 'ent', result: parse(path, text) });

const userGo = `
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

// User holds the schema definition for the User entity.
type User struct {
	ent.Schema
}

func (User) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").Unique().Comment("display name"),
		field.Int("age").Optional(),
		field.String("nick").StorageKey("nickname"),
		field.Enum("status").Values("active", "inactive").Default("active"),
	}
}

func (User) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "users"},
	}
}

func (User) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("name").Unique(),
	}
}
`;

const carGo = `
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/edge"
)

type Car struct {
	ent.Schema
}

func (Car) Fields() []ent.Field {
	return []ent.Field{
		field.String("model"),
	}
}

func (Car) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("owner", User.Type).Ref("cars").Unique().Field("owner_id"),
	}
}
`;

const blogGo = `
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
)

type Blog struct {
	ent.Schema
}

func (Blog) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("posts", Post.Type),
		edge.To("avatar", Image.Type).Unique(),
	}
}
`;

const mixinGo = `
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/mixin"
)

type TimeMixin struct {
	mixin.Schema
}

func (TimeMixin) Fields() []ent.Field {
	return []ent.Field{
		field.Time("created_at").Immutable(),
		field.Time("updated_at"),
	}
}

type Post struct {
	ent.Schema
}

func (Post) Mixin() []ent.Mixin {
	return []ent.Mixin{
		TimeMixin{},
	}
}

func (Post) Fields() []ent.Field {
	return []ent.Field{
		field.String("title"),
	}
}
`;

const migrateGo = `
// Code generated by ent, DO NOT EDIT.
package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "age", Type: field.TypeInt, Nullable: true},
	}
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	CarsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "model", Type: field.TypeString},
		{Name: "owner_id", Type: field.TypeInt, Nullable: true},
	}
	CarsTable = &schema.Table{
		Name:       "cars",
		Columns:    CarsColumns,
		PrimaryKey: []*schema.Column{CarsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "cars_users_cars",
				Columns:    []*schema.Column{CarsColumns[2]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
)

func init() {
	CarsTable.ForeignKeys[0].RefTable = UsersTable
}
`;

describe('ent detect', () => {
  it('claims files importing entgo.io/ent', () => {
    expect(entParser.detect({ path: 'user.go', text: userGo })).toBe(true);
    expect(entParser.detect({ path: 'migrate/schema.go', text: migrateGo })).toBe(true);
  });

  it('ignores GORM / Bun neighbours', () => {
    expect(entParser.detect({ path: 'g.go', text: 'package m\nimport "gorm.io/gorm"\ntype U struct { gorm.Model }' })).toBe(false);
    expect(entParser.detect({ path: 'b.go', text: 'package m\nimport "github.com/uptrace/bun"' })).toBe(false);
  });
});

describe('ent schema files', () => {
  const result = parse('ent/schema/user.go', userGo);
  const user = result.entities[0];

  it('reads the annotation table name, implicit id PK and field attributes', () => {
    expect(user).toMatchObject({ name: 'users', modelName: 'User', nameCertainty: 2, comment: 'User holds the schema definition for the User entity.' });
    expect(user.columns.map((c) => c.name)).toEqual(['id', 'name', 'age', 'nickname', 'status']);
    expect(user.columns.find((c) => c.name === 'id')).toMatchObject({ type: 'int', primaryKey: true, nullable: false, generated: true });
    expect(user.columns.find((c) => c.name === 'name')).toMatchObject({ type: 'string', unique: true, nullable: false, comment: 'display name' });
    expect(user.columns.find((c) => c.name === 'age')).toMatchObject({ type: 'int', nullable: true });
    expect(user.columns.find((c) => c.name === 'nickname')).toMatchObject({ type: 'string', nullable: false });
  });

  it('emits an enum for field.Enum and links the column', () => {
    expect(result.enums).toEqual([expect.objectContaining({ name: 'users_status', values: ['active', 'inactive'] })]);
    expect(user.columns.find((c) => c.name === 'status')).toMatchObject({ enumRef: 'users_status', generated: true });
  });

  it('reads indexes', () => {
    expect(user.indexes).toEqual([{ columns: ['name'], unique: true }]);
  });

  it('reads edge.From as a many-to-one with the FK column on this entity', () => {
    const car = parse('ent/schema/car.go', carGo);
    expect(car.entities[0]).toMatchObject({ name: 'cars', modelName: 'Car', nameCertainty: 0 });
    expect(car.entities[0].columns.map((c) => c.name)).toEqual(['id', 'model', 'owner_id']);
    expect(car.relations).toEqual([
      expect.objectContaining({ from: { model: 'Car' }, fromColumns: ['owner_id'], to: { model: 'User' }, cardinality: 'many-to-one' }),
    ]);
  });

  it('reads edge.To as one-to-many and edge.To().Unique() as one-to-one with Ent default FK columns', () => {
    const blog = parse('ent/schema/blog.go', blogGo);
    expect(blog.relations.find((r) => r.to.model === 'Post')).toMatchObject({ from: { model: 'Blog' }, toColumns: ['blog_posts'], cardinality: 'one-to-many' });
    expect(blog.relations.find((r) => r.from.model === 'Image')).toMatchObject({ to: { model: 'Blog' }, fromColumns: ['blog_avatar'], cardinality: 'one-to-one' });
  });

  it('does not throw on malformed input', () => {
    expect(() => parse('x.go', 'package schema\nimport "entgo.io/ent"\ntype T struct { ent.Schema }\nfunc (T) Fields() []ent.Field { return []ent.Field{ field.String( } }')).not.toThrow();
  });
});

describe('ent mixins', () => {
  it('copies mixin fields into the model via abstract base + extends', () => {
    const r = resolveSchema([fr('ent/schema/mixin.go', mixinGo)]);
    const post = r.entities.find((e) => e.id === 'posts')!;
    expect(post.columns.map((c) => c.name).sort()).toEqual(['created_at', 'id', 'title', 'updated_at']);
    // the abstract mixin itself is not a table
    expect(r.entities.find((e) => e.modelNames.includes('TimeMixin'))).toBeUndefined();
  });
});

describe('ent migrate/schema.go', () => {
  const result = parse('ent/migrate/schema.go', migrateGo);

  it('reads explicit columns, primary keys and foreign keys', () => {
    const cars = result.entities.find((e) => e.name === 'cars')!;
    expect(cars.nameCertainty).toBe(2);
    expect(cars.columns.map((c) => c.name)).toEqual(['id', 'model', 'owner_id']);
    const users = result.entities.find((e) => e.name === 'users')!;
    expect(users.columns.find((c) => c.name === 'name')).toMatchObject({ type: 'varchar(255)', unique: true });
    expect(users.columns.find((c) => c.name === 'id')).toMatchObject({ primaryKey: true, generated: true });
    expect(result.relations).toEqual([
      expect.objectContaining({ from: { name: 'cars' }, fromColumns: ['owner_id'], to: { name: 'users' }, toColumns: ['id'], cardinality: 'many-to-one', onDelete: 'SET NULL', kind: 'foreign-key' }),
    ]);
  });
});

describe('ent end-to-end (schema files + generated migrate)', () => {
  it('merges both sources into clean entities, columns, relation and enum', () => {
    const r = resolveSchema([fr('ent/schema/user.go', userGo), fr('ent/schema/car.go', carGo), fr('ent/migrate/schema.go', migrateGo)]);
    expect(r.entities.map((e) => e.id).sort()).toEqual(['cars', 'users']);

    const users = r.entities.find((e) => e.id === 'users')!;
    expect(users.columns.map((c) => c.name)).toEqual(['id', 'name', 'age', 'nickname', 'status']);
    expect(users.columns.find((c) => c.name === 'status')!.enumRef).toBe('users_status');

    const cars = r.entities.find((e) => e.id === 'cars')!;
    expect(cars.columns.find((c) => c.name === 'owner_id')!.references).toEqual({ entity: 'users', column: 'id' });

    expect(r.relations).toHaveLength(1);
    expect(r.relations[0]).toMatchObject({ from: 'cars', to: 'users', fromColumns: ['owner_id'], cardinality: 'many-to-one', onDelete: 'SET NULL', kind: 'foreign-key', optional: true });

    expect(r.enums.map((e) => e.name)).toEqual(['users_status']);
  });
});
